"""initial db

Revision ID: 14d30ae938bb
Revises: 
Create Date: 2026-01-21 16:10:44.442555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d30ae938bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_sheets_id'), 'balance_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_balance_sheets_symbol'), 'balance_sheets', ['symbol'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flows_symbol'), 'cash_flows', ['symbol'], unique=False)
    op.create_table('company_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_events_id'), 'company_events', ['id'], unique=False)
    op.create_index(op.f('ix_company_events_symbol'), 'company_events', ['symbol'], unique=False)
    op.create_table('company_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_news_id'), 'company_news', ['id'], unique=False)
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_company_profiles_symbol'), 'company_profiles', ['symbol'], unique=True)
    op.create_table('foreign_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('net_buy_sell', sa.Float(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_transactions_id'), 'foreign_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_foreign_transactions_symbol'), 'foreign_transactions', ['symbol'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_statements_id'), 'income_statements', ['id'], unique=False)
    op.create_index(op.f('ix_income_statements_symbol'), 'income_statements', ['symbol'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('insider_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_transactions_id'), 'insider_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_insider_transactions_symbol'), 'insider_transactions', ['symbol'], unique=False)
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('changed_percent', sa.String(length= 100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_data_id'), 'macro_data', ['id'], unique=False)
    op.create_table('macro_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_news_id'), 'macro_news', ['id'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_listings_id'), 'market_listings', ['id'], unique=False)
    op.create_index(op.f('ix_market_listings_symbol'), 'market_listings', ['symbol'], unique=True)
    op.create_table('market_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sectors_id'), 'market_sectors', ['id'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_index(op.f('ix_officers_symbol'), 'officers', ['symbol'], unique=False)
    op.create_table('ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratios_id'), 'ratios', ['id'], unique=False)
    op.create_index(op.f('ix_ratios_symbol'), 'ratios', ['symbol'], unique=False)
    op.create_table('shareholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('shareholder_name', sa.String(length=255), nullable=True),
    sa.Column('ownership_percent', sa.Float(), nullable=True),
    sa.Column('shares_owned', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholders_id'), 'shareholders', ['id'], unique=False)
    op.create_index(op.f('ix_shareholders_symbol'), 'shareholders', ['symbol'], unique=False)
    op.create_table('top_movers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_movers_id'), 'top_movers', ['id'], unique=False)
    op.create_index(op.f('ix_top_movers_symbol'), 'top_movers', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_movers_symbol'), table_name='top_movers')
    op.drop_index(op.f('ix_top_movers_id'), table_name='top_movers')
    op.drop_table('top_movers')
    op.drop_index(op.f('ix_shareholders_symbol'), table_name='shareholders')
    op.drop_index(op.f('ix_shareholders_id'), table_name='shareholders')
    op.drop_table('shareholders')
    op.drop_index(op.f('ix_ratios_symbol'), table_name='ratios')
    op.drop_index(op.f('ix_ratios_id'), table_name='ratios')
    op.drop_table('ratios')
    op.drop_index(op.f('ix_officers_symbol'), table_name='officers')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_market_sectors_id'), table_name='market_sectors')
    op.drop_table('market_sectors')
    op.drop_index(op.f('ix_market_listings_symbol'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_macro_news_id'), table_name='macro_news')
    op.drop_table('macro_news')
    op.drop_index(op.f('ix_macro_data_id'), table_name='macro_data')
    op.drop_table('macro_data')
    op.drop_index(op.f('ix_insider_transactions_symbol'), table_name='insider_transactions')
    op.drop_index(op.f('ix_insider_transactions_id'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_income_statements_symbol'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_id'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_foreign_transactions_symbol'), table_name='foreign_transactions')
    op.drop_index(op.f('ix_foreign_transactions_id'), table_name='foreign_transactions')
    op.drop_table('foreign_transactions')
    op.drop_index(op.f('ix_company_profiles_symbol'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_index(op.f('ix_company_news_id'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index(op.f('ix_company_events_symbol'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_id'), table_name='company_events')
    op.drop_table('company_events')
    op.drop_index(op.f('ix_cash_flows_symbol'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_balance_sheets_symbol'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_id'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
