"""change macro table

Revision ID: 82711b992d94
Revises: 9dc0729ea6b0
Create Date: 2026-01-21 08:54:44.559079+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82711b992d94'
down_revision: str = '9dc0729ea6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_data')
    op.drop_index(op.f('ix_officers_symbol'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_foreign_transactions_symbol'), table_name='foreign_transactions')
    op.drop_table('foreign_transactions')
    op.drop_index(op.f('ix_company_events_symbol'), table_name='company_events')
    op.drop_table('company_events')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_insider_transactions_symbol'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_shareholders_symbol'), table_name='shareholders')
    op.drop_table('shareholders')
    op.drop_table('macro_news')
    op.drop_index(op.f('ix_balance_sheets_symbol'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    op.drop_index(op.f('ix_income_statements_symbol'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index(op.f('ix_cash_flows_symbol'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_ratios_symbol'), table_name='ratios')
    op.drop_table('ratios')
    op.drop_table('market_sectors')
    op.drop_index(op.f('ix_top_movers_symbol'), table_name='top_movers')
    op.drop_table('top_movers')
    op.drop_index(op.f('ix_company_profiles_symbol'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('company_profiles_pkey')),
    sa.UniqueConstraint('symbol', name=op.f('company_profiles_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_company_profiles_symbol'), 'company_profiles', ['symbol'], unique=False)
    op.create_table('top_movers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('price_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percent_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('top_movers_pkey'))
    )
    op.create_index(op.f('ix_top_movers_symbol'), 'top_movers', ['symbol'], unique=False)
    op.create_table('market_sectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sector_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_sectors_pkey'))
    )
    op.create_table('ratios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ratios_pkey'))
    )
    op.create_index(op.f('ix_ratios_symbol'), 'ratios', ['symbol'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_flows_pkey'))
    )
    op.create_index(op.f('ix_cash_flows_symbol'), 'cash_flows', ['symbol'], unique=False)
    op.create_table('company_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('company_news_pkey'))
    )
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('income_statements_pkey'))
    )
    op.create_index(op.f('ix_income_statements_symbol'), 'income_statements', ['symbol'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('balance_sheets_pkey'))
    )
    op.create_index(op.f('ix_balance_sheets_symbol'), 'balance_sheets', ['symbol'], unique=False)
    op.create_table('macro_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('macro_news_pkey'))
    )
    op.create_table('shareholders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('shareholder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ownership_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shares_owned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shareholders_pkey'))
    )
    op.create_index(op.f('ix_shareholders_symbol'), 'shareholders', ['symbol'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('insider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('insider_transactions_pkey'))
    )
    op.create_index(op.f('ix_insider_transactions_symbol'), 'insider_transactions', ['symbol'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_listings_pkey')),
    sa.UniqueConstraint('symbol', name=op.f('market_listings_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('company_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('company_events_pkey'))
    )
    op.create_index(op.f('ix_company_events_symbol'), 'company_events', ['symbol'], unique=False)
    op.create_table('foreign_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('net_buy_sell', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('buy_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sell_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('foreign_transactions_pkey'))
    )
    op.create_index(op.f('ix_foreign_transactions_symbol'), 'foreign_transactions', ['symbol'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('officers_pkey'))
    )
    op.create_index(op.f('ix_officers_symbol'), 'officers', ['symbol'], unique=False)
    op.create_table('macro_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('macro_data_pkey'))
    )
    # ### end Alembic commands ###